meson: Check for __get_cpuid
checking for presence of cpuid.h header alone is not sufficient in some case to use
cpuid related functions. e.g. when using clang which is built for
multiple targets will have cpuid.h header as part of compiler headers in
distribution but one maybe compiling pulseaudion for non-x86 target. The
current check in meson succeeds and then compile fails later because
cpuid.h is x86-specific header. Therefore checking for symbol that is
needed makes this robust, so even if header exist it will try to ensure
the given symbol can be used

Fixes
src/pulsecore/core-util.c:113:
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/pulseaudio/14.0-r0/recipe-sysroot-native/usr/lib/clang/11.0.1/include/cpuid.h:11:2: error: this header is for x86 only
| #error this header is for x86 only
|  ^

Imported from:
https://git.openembedded.org/openembedded-core/tree/meta/recipes-multimedia/pulseaudio/pulseaudio/0001-meson-Check-for-__get_cpuid.patch?h=kirkstone&id=29bf058368e4a6336b74d9aa6880d3176cadb913

Change-Id: Ia91e6897b300586d7da397f013be81beef6d7817
Signed-off-by: Khem Raj <raj.khem@gmail.com>
Cc: Tanu Kaskinen <tanuk@iki.fi>