[OSE] Fix qemu build error: 'ePhysicalSink_a2dp' undeclared
:Release Notes:
error: 'ePhysicalSink_a2dp' undeclared in qemu is fixed

:Detailed Notes:
'ePhysicalSink_a2dp' is added in i386 enum to fix the build error

:Testing Performed:
Build error is fixed for qemu

:QA Notes:
NA

:Issues Addressed:
[PLAT-84615] [OSE] Fix qemu build error

Change-Id: I285a36c874c2771403ae00ca9ce135c2b69ef032